[alias]
xtask = "run --package xtask --"

[target.riscv32imc-unknown-none-elf]
runner = "espflash flash --monitor"

[target.riscv32imac-unknown-none-elf]
runner = "espflash flash --monitor"

[env]
ESP_LOG="INFO"
# Disabling PHY USB passthrough improves WiFi reliability on ESP32-C6
ESP_RADIO_CONFIG_PHY_ENABLE_USB="false"

[build]
rustflags = [
  "-C", "force-frame-pointers",
]
