[target.riscv32imc-unknown-none-elf]
runner = "espflash flash --monitor"

[target.riscv32imac-unknown-none-elf]
runner = "espflash flash --monitor"

[env]
ESP_LOG="INFO"

[build]
rustflags = [
  "-C", "force-frame-pointers",
]

[unstable]
build-std = ["alloc", "core"]
